//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessOutputReader.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessOutputReader.Infrastructure.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменено выполнение команды &quot;{0}&quot;..
        /// </summary>
        internal static string CommandExecutionCanceled {
            get {
                return ResourceManager.GetString("CommandExecutionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск выполнения команды невозможен, т.к. она находится в недопустимом состоянии..
        /// </summary>
        internal static string CommandExecutionCannotStarted {
            get {
                return ResourceManager.GetString("CommandExecutionCannotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение команды не было завершено..
        /// </summary>
        internal static string CommandExecutionNotCompleted {
            get {
                return ResourceManager.GetString("CommandExecutionNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение команды не было завершено, т.к. команда была отменена..
        /// </summary>
        internal static string CommandExecutionNotCompletedDueToCancellation {
            get {
                return ResourceManager.GetString("CommandExecutionNotCompletedDueToCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение команды не было завершено за установленный период времени. Таймаут: &quot;{0}&quot;..
        /// </summary>
        internal static string CommandExecutionTimeout {
            get {
                return ResourceManager.GetString("CommandExecutionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое состояние конечного автомата..
        /// </summary>
        internal static string InvalidStateOfStateMachine {
            get {
                return ResourceManager.GetString("InvalidStateOfStateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процесс &quot;{0}&quot; не был запущен..
        /// </summary>
        internal static string ProcessNotStarted {
            get {
                return ResourceManager.GetString("ProcessNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановка процесса &quot;{0}&quot; не была выполнена..
        /// </summary>
        internal static string ProcessNotStopped {
            get {
                return ResourceManager.GetString("ProcessNotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск получения данных от процесса не был завершен..
        /// </summary>
        internal static string StartReceivingDataNotCompleted {
            get {
                return ResourceManager.GetString("StartReceivingDataNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановка получения данных от процесса не была завершена..
        /// </summary>
        internal static string StopReceivingDataNotCompleted {
            get {
                return ResourceManager.GetString("StopReceivingDataNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестное значение перечисления &quot;{0}&quot;..
        /// </summary>
        internal static string UnknownEnumValue {
            get {
                return ResourceManager.GetString("UnknownEnumValue", resourceCulture);
            }
        }
    }
}
